In [12]:
import numpy as np

arr1 = np.array([1,2,3,4])
print("Before appending the value to the array: ",arr1) # here it just prints the default arr1 value
print("\n")
# in here it appends 5 to arr1 in the last index and prints the total array
print("after printing the value to the default array: ",np.append(arr1,5)) 

Before appending the value to the array:  [1 2 3 4]


after printing the value to the default array:  [1 2 3 4 5]


In [18]:
# in 2-D array
#in 2D array first it converts 2D into 1D and appends the value to the array
arr1 = np.array([[1,2],[3,4]])
print(arr1)
print("\n")
print("after converting it & appending the value: ",np.append(arr1,6))

[[1 2]
 [3 4]]


after converting it & appending the value:  [1 2 3 4 6]


In [19]:
# in 2-D array
#in 2D array first it converts 2D into 1D and appends the value to the array
arr1 = np.array([[1,2],[3,4]])
print(arr1)
print("\n")
print("after converting it & appending the value: ",np.append(arr1,[6,7]))

[[1 2]
 [3 4]]


after converting it & appending the value:  [1 2 3 4 6 7]


In [22]:
# here it is inserting the given value into the 2nd index using the (np.insert) function (array,index,value)

a = np.array([1,2,3,4])
print(np.insert(a,2,6)) 

[1 2 6 3 4]


In [24]:
# here it is inserting the given value into the 2nd index using the (np.insert) function (array,index,value)

a = np.array([[1,2],[3,4]])
print(np.insert(a,2,[6,7])) 

[1 2 6 7 3 4]


In [31]:
# deletion
a = np.array([[1,2],[3,4]])
print(np.delete(a,1,axis = 0))

[[1 2]]
