In [1]:
import numpy as np

a = np.array([1,2,3,4])

# to print the sum of the array for 1D array
print(np.sum(a))

15


In [3]:
a = np.array([1,2,3,4])

# to print the minimum value from the array for 1D array
print(np.min(a))

1


In [4]:
# to print the maximum value from the array for 1D array
print(np.max(a))

4


In [5]:
# to print the count of the array we use the function as (size) for 1D array

print(np.size(a))

4


In [6]:
# to print the mean, median & mode using the array for 1D array
 
print(np.mean(a))

2.5


In [8]:
print(np.cumsum(a)) # Cummilative sum for 1D array

[ 1  3  6 10]


In [9]:
print(np.cumprod(a)) # Cummilative product for 1D array

[ 1  2  6 24]


In [17]:
# now the same funtions used above but now with 2D array

a = np.array([[1,2],[3,4]])

print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.size(a))
print(np.mean(a))
print(np.cumsum(a))
print(np.cumprod(a))

10
1
4
4
2.5
[ 1  3  6 10]
[ 1  2  6 24]


In [29]:
a = [100,150,199,200,250,130]
b = [10,50,30,40,30,10]

price = np. array(a)
quantity = np. array (b)

print (price,"\n",quantity)
print()

c = np.cumprod([price, quantity],axis = 0)

print(c)
print()
print(c[1].sum())

[100 150 199 200 250 130] 
 [10 50 30 40 30 10]

[[ 100  150  199  200  250  130]
 [1000 7500 5970 8000 7500 1300]]

31270
