In [3]:
import numpy as np

arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([1,3,5,7,8,9])
print(arr1) # here it is printing the array which is arr1
print("\n")
print(np.add(arr1,arr2))  # in arrays it is adding up whole arr1 and arr2

[1 2 3 4 5 6]


[ 2  5  8 11 13 15]


In [4]:
# while in lists when we add up (a+b) it actually concatenates or join's the two lists(a,b)
a = (1,2,3,4)
b = (2,3,4,5)
print(a+b)

(1, 2, 3, 4, 2, 3, 4, 5)


In [11]:
# in arrays we can also concatenate two arrays using (np.concatenate) function 
import numpy as np

arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[1,3,5],[7,8,9]])
print(np.concatenate([arr1,arr2])) 

[[1 2 3]
 [4 5 6]
 [1 3 5]
 [7 8 9]]


In [18]:
# axis is nothing but to concatenate the arrays of (arr1,arr2) in a vertical manner (method - 1)

print(np.concatenate([arr1,arr2],axis = 0))

[[1 2 3]
 [4 5 6]
 [1 3 5]
 [7 8 9]]


In [13]:
# axis is nothing but to concatenate the arrays of (arr1,arr2) in a horizontal manner (method - 2)

print(np.concatenate([arr1,arr2],axis = 1)) 

[[1 2 3 1 3 5]
 [4 5 6 7 8 9]]


In [16]:
print(np.hstack([arr1,arr2]))  # for horizonally concatenate (method - 1)

[[1 2 3 1 3 5]
 [4 5 6 7 8 9]]


In [17]:
print(np.vstack([arr1,arr2])) # vertical concatenation (method - 2)

[[1 2 3]
 [4 5 6]
 [1 3 5]
 [7 8 9]]


In [24]:
# for splitting the array we have 

arr1 = np.array([1,2,3,4])
print(np.array_split(arr1,3))
print("\n")
print(np.array_split(arr1,2))
print("\n")
print(np.array_split(arr1,4))

[array([1, 2]), array([3]), array([4])]


[array([1, 2]), array([3, 4])]


[array([1]), array([2]), array([3]), array([4])]


In [37]:
arr1 = np.array([[1,2,3],[4,5,6]])
b = np.array_split(arr1,2)
print(b)
print("\n")
print(b[1]) # splitting the array forst and printing the index of splitted array (a,3) 3 here says how many parts

[array([[1, 2, 3]]), array([[4, 5, 6]])]


[[4 5 6]]
