In [2]:
import numpy as np

In [5]:
arr1 = np.array([30,40,50,60,70])
arr2 = np.array([10,20,20,40,50])

print(arr1+arr2) # for printing the addition of arrays

[ 40  60  70 100 120]


In [6]:
print(np.add(arr1,arr2)) #we can also add-up arrays using (np.add) function also

[ 40  60  70 100 120]


In [8]:
arr1 = np.array([[30,40],[50,60]])
arr2 = np.array([[10,20],[20,40]])

print(arr1 + arr2) # if we pass seperate arrays and print them this will be the output

[[ 40  60]
 [ 70 100]]


In [12]:
arr1 = np.array([[30,40],[50,60]])
arr2 = np.array([[10,20],[20,40]])

print(arr1 - arr2)
print("\n")
print(np.subtract(arr1,arr2)) # as the same way of addition we can also perform subtraction or difference between two arrays

[[20 20]
 [30 20]]


[[20 20]
 [30 20]]


In [15]:
arr1 = np.array([[30,40],[50,60]])
arr2 = np.array([[10,20],[20,40]])

print(arr1 * arr2)
print("\n")
print(np.multiply(arr1,arr2)) # as the same way of addition we can also perform multiplication between two arrays

[[ 300  800]
 [1000 2400]]


[[ 300  800]
 [1000 2400]]


In [17]:
arr1 = np.array([[30,40],[50,60]])
arr2 = np.array([[10,20],[20,40]])

print(arr1 / arr2)
print("\n")
print(np.divide(arr1,arr2)) # as the same way of addition we can also perform division between two arrays


[[3.  2. ]
 [2.5 1.5]]


[[3.  2. ]
 [2.5 1.5]]


In [23]:
arr1 = np.array([3,4,5,6])
arr2 = np.array([2])

print(np.power(arr1,arr2)) # by this we can also perform power functions ex: (30 pw 3 is 27000)

[ 9 16 25 36]


In [24]:
arr1 = np.array([9,16,25,36])
print(np.sqrt(arr1)) #in this way we can also perform square root in this it resulted in the form of float we can convert it using astype(int)

[3. 4. 5. 6.]
