In [8]:
import numpy as np

a = [[20,30,10],[40,50,10]]
arr = np.array(a)
print(arr)

[[20 30 10]
 [40 50 10]]


In [9]:
#Functions to inspect the particular Array
print(arr)
print(arr.shape) # To determine the shape of the array 2 rows & 3 columns

[[20 30 10]
 [40 50 10]]
(2, 3)


In [10]:
print(arr)
print(arr.size) # To determine the size of the array which is 3+3

[[20 30 10]
 [40 50 10]]
6


In [11]:
print(arr)
print(arr.ndim) # (ndim) is nothing but it tells all about which dimensional array is it, in our case it is 2-dimensional array

[[20 30 10]
 [40 50 10]]
2


In [12]:
print(arr)
print(len(arr)) # it gives length of the array which says how many array's are there in the given thing, number of nested values

[[20 30 10]
 [40 50 10]]
2


In [13]:
print(arr)
print(arr.dtype)  # in this case it will give us the Data Type of the array but these two are the similar which gives us type of the array.

[[20 30 10]
 [40 50 10]]
int64


In [15]:
print(arr)
print(type(arr)) # In this case it will give the type of numpy array

[[20 30 10]
 [40 50 10]]
<class 'numpy.ndarray'>


In [23]:
print("before converting the array: ", "\n", arr)
print("\n")
print("after converting the array: ", "\n", arr.astype(float)) # In this case it is actually converting the data type of array which is int (integer) to Float (decimal points).
print("\n")
print(type(arr))

before converting the array:  
 [[20 30 10]
 [40 50 10]]


after converting the array:  
 [[20. 30. 10.]
 [40. 50. 10.]]


<class 'numpy.ndarray'>
