In [5]:
import numpy as np

a = np.array([[1,6,10,14,9,4],[2,8,5,1,3,4]])
print(a)

[[ 1  6 10 14  9  4]
 [ 2  8  5  1  3  4]]


In [6]:
# for sorting the array for 1D & 2D
print(np.sort(a))

[[ 1  4  6  9 10 14]
 [ 1  2  3  4  5  8]]


In [10]:
# search in array
b = np.array([3,4,1,7,8])
s = np.where(b % 2 == 0)
print(s)

(array([1, 4]),)


In [12]:
# Sorted search (searchsorted)

b = np.array([3,4,1,7,8])
s = np.searchsorted(b,8)
print(s)

4


In [13]:
# Filter (important) we would be using Booleean values in Filter

a = np.array([1,2,3,4])
fa = [True, False, True, False] # how many times the (True & False) values are there then the equal values should be in the array
new = a[fa]
print(new)

[1 3]


In [14]:
# Filter (important) we would be using Booleean values in Filter

a = np.array([1,2,3,4])
fa = [True, False, False, False] # how many times the (True & False) values are there then the equal values should be in the array
new = a[fa]
print(new)

[1]


In [19]:
a = np.array([1,2,3,4,5])
fa = a % 2 == 1
new = a[fa]
print(new)

[1 3 5]
